config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy' 

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/gigs/most_recent', to: 'gigs#most_recent'

  get '/users/contractors', to: 'users#contractors'



  get '/gigs/highest_paying', to: 'gigs#highest_paying'

  # resources :users
  resources :gigs, only: [:index, :show, :create, :update, :destroy]
  
  resources :requests

  resources :users do
    resources :gigs, only: [:index, :show, :new, :create, :edit, :update]

  end 
end

app/models/user.rb
class User < ApplicationRecord
   
    has_many :requests, inverse_of: :user
    has_many :posted_gigs, through: :requests, source: :gig
    
    has_many :gigs

    validates :first_name, :last_name, :email, presence: true
    validates :email, uniqueness: true

    scope :contractor, -> { where(contractor: 'true') }

    has_secure_password 


    def self.find_or_create_by_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.first_name = auth['info']['first_name']
            u.last_name = auth['info']['last_name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex
        end
    end

    def full_name
        self.first_name + " " + self.last_name
    end

    def authorized_contractor
        self.contractor = true && current_user = self
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorized_to_modify_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/login'
    else
      render :new
    end
  end

  def show
    @requests = Request.show_requests(@user)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def contractors
    @contractors = User.contractor
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :instrument,
      :bio,
      :contractor,
      :password
    )
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def authorized_to_modify_user
    if !@user 
      flash[:unauthorized] = "You are not authorized to modify this user."
      redirect_to '/'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

    def welcome_header
        if current_user
            "Welcome, #{current_user.first_name}!" 
        end
    end

    def contractor_header
        if @user.contractor && @user == current_user
            "== CONTRACTOR STATUS =="
        end
    end

    def meet_musicians
        if @user != current_user 
            "== Meet Your Fellow Musician =="
        end
    end

    def authorized_to_update_user
        if authorized?(@user)
        tag.p(button_to('Update Your Profile', edit_user_path(current_user), method: :get))
        end
    end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <p><%= f.label :first_name %>
    <%= f.text_field :first_name %></p>

    <p><%= f.label :last_name %>
    <%= f.text_field :last_name %></p>

    <p><%= f.label :email %>
    <%= f.email_field :email %></p>

    <p><%= f.label :password %>
    <%= f.password_field :password %></p>
    
    <%= f.submit %>

<% end %>

app/views/users/_user_info.html.erb
<h3><%= @user.full_name %></h3>
<h4>Instrument: </h4>
<p><%= @user.instrument %></p>
<h4>Bio: </h4>
<p><%= @user.bio %></p>
<h4>Contact: </h4>
<p><%= @user.email %></p>

app/views/users/_users.html.erb
<% users.each do |user| %>
<li><%= link_to user.full_name, user_path(user) %>
<% end %>

app/views/users/contractors.html.erb
<h1>List of Contractors </h1>

<%= render partial: "users", locals: { users: @contractors } %>

app/views/users/edit.html.erb
<h3 style="color:DarkRed;"><%= flash[:update] %></h3> 
<%= render partial: "layouts/errors", locals: { object: @user } %>

<h1>Edit Profile</h1>


<%= form_for @user do |f| %>

    <p><%= f.label :first_name %>
    <%= f.text_field :first_name %></p>

    <p><%= f.label :last_name %>
    <%= f.text_field :last_name %></p>

    <p><%= f.label :email %>
    <%= f.email_field :email %></p>   
    
    <p><%= f.label :instrument %>
    <%= f.text_field :instrument %></p>

    <p><%= f.label :bio %>
    <%= f.text_area :bio %></p>

    <p><%= f.label "Check box if you are a contractor" %>
    <%= f.check_box :contractor %></p>

    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Meet Fellow Musicians! </h1>

<%= render partial: "users", locals: { users: @users } %>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: { object: @user } %>
<h3 style="color:DarkRed;"><%= flash[:message] %></h3> 

<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h3 style="color:DarkOliveGreen;"> <%= flash[:delete] %></h3>

<h1><%= welcome_header %></h1>

<h3><%= contractor_header %></h3>
        
<h2><%= meet_musicians %></h2>

<%= render 'user_info' %>

<%= authorized_to_update_user %>

<% if authorized?(@user) && @user.contractor %>
    <h3>Gig Applications Received: </h3>
        <% @requests.each do |request| %>
            <li><%= link_to request.user_name, user_path(request.user) %> for <%= link_to request.gig_name, gig_path(request.gig) %></li>
        <% end%>
    <% end %>
    
<% if authorized?(@user) && !@user.contractor %>
    <h3>Gig Applications Submitted: </h3>
        <% @user.requests.each do |request| %>
            <li><%= link_to request.gig_name, gig_path(request.gig_id) %>
    <% end %>
<% end %>