config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy' 

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/gigs/most_recent', to: 'gigs#most_recent'

  get '/users/contractors', to: 'users#contractors'



  get '/gigs/highest_paying', to: 'gigs#highest_paying'

  # resources :users
  resources :gigs, only: [:index, :show, :create, :update, :destroy]
  
  resources :requests

  resources :users do
    resources :gigs, only: [:index, :show, :new, :create, :edit, :update]

  end 
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Sacramento
          ">
    <style>
      body {
        font-family: 'Sacramento';
        font-size: 20px;
      }
    </style>
    <title>FreelanceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">

        <a class="navbar-brand" href="<%= root_path %>"/>Home</a> |
        <% if logged_in? %>
          <a class="navbar-brand" href="<%= user_path(current_user) %>"/><%= current_user.first_name %>'s Profile</a>  |
          <a class="navbar-brand" href="<%= gigs_path %>"/>Upcoming Gigs</a>  |
          <a class="nvabar-brand" href="<%= users_path %>"/> Meet Fellow Musicians</a>   |                       
          <a class="navbar-brand" href="<%= users_contractors_path %>"/>Meet Contractors</a>  |
          <%= link_to "Log Out", logout_path, class:"navbar-brand",method: :post %>   |

        <% if logged_in? && current_user.contractor %>
          <a class="navbar-brand" href="<%= user_gigs_path(current_user) %>"/>Your Posted Gigs</a>   |
        <% end %>

        <% if current_user.contractor %>
          <a class="navbar-brand" href="<%= new_user_gig_path(current_user) %>"/>Create New Gig</a>  
        <% end %>
   
        <% else %>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>   |
          <a class="navbar-brand" href="<%= login_path %>"/>Log In</a>   |
          <%= link_to "Log In with Google", '/auth/google_oauth2', class:"navbar-brand", method: :post %> |
        <% end %>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>

    </div>
  </body>
</html>